# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registracija.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui_login
import Korisnik

class Ui_Registracija(QtWidgets.QDialog):
    def __init__(self):
        QtWidgets.QDialog.__init__(self)
        self.setupUi(self)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 697)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(32)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.txtKorisnickoIme = QtWidgets.QLineEdit(Dialog)
        self.txtKorisnickoIme.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtKorisnickoIme.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.txtKorisnickoIme)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.txtLozinka = QtWidgets.QLineEdit(Dialog)
        self.txtLozinka.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtLozinka.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.txtLozinka)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.txtIme = QtWidgets.QLineEdit(Dialog)
        self.txtIme.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtIme.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.txtIme)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.txtPrezime = QtWidgets.QLineEdit(Dialog)
        self.txtPrezime.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtPrezime.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.txtPrezime)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.txtDrzava = QtWidgets.QLineEdit(Dialog)
        self.txtDrzava.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtDrzava.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.txtDrzava)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.txtAdresa = QtWidgets.QLineEdit(Dialog)
        self.txtAdresa.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtAdresa.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.txtAdresa)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.txtEmail = QtWidgets.QLineEdit(Dialog)
        self.txtEmail.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtEmail.setObjectName("lineEdit_7")
        self.horizontalLayout_6.addWidget(self.txtEmail)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.txtBrojKartice = QtWidgets.QLineEdit(Dialog)
        self.txtBrojKartice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtBrojKartice.setObjectName("lineEdit_8")
        self.horizontalLayout_10.addWidget(self.txtBrojKartice)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.txtBrojTelefona = QtWidgets.QLineEdit(Dialog)
        self.txtBrojTelefona.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtBrojTelefona.setObjectName("lineEdit_9")
        self.horizontalLayout.addWidget(self.txtBrojTelefona)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.txtPostanskiBroj = QtWidgets.QLineEdit(Dialog)
        self.txtPostanskiBroj.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtPostanskiBroj.setObjectName("Postanski broj")
        self.horizontalLayout_11.addWidget(self.txtPostanskiBroj)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.registracijaKorisnika)
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Registracija"))
        self.label_2.setText(_translate("Dialog", "Korisničko ime: "))
        self.label_3.setText(_translate("Dialog", "Lozinka: "))
        self.label_4.setText(_translate("Dialog", "Ime: "))
        self.label_5.setText(_translate("Dialog", "Prezime: "))
        self.label_6.setText(_translate("Dialog", "Država: "))
        self.label_7.setText(_translate("Dialog", "Adresa: "))
        self.label_8.setText(_translate("Dialog", "Email"))
        self.label_9.setText(_translate("Dialog", "Broj kartice: "))
        self.label_10.setText(_translate("Dialog", "Broj telefona: "))
        self.label_11.setText(_translate("Dialog", "Poštanski broj: "))
        self.pushButton.setText(_translate("Dialog", "Registriraj se"))

    def registracijaKorisnika(self):
        korisnickoIme = self.txtKorisnickoIme.text()
        lozinka = self.txtLozinka.text()
        ime = self.txtIme.text()
        prezime = self.txtPrezime.text()
        drzava = self.txtDrzava.text()
        postanskiBroj = self.txtPostanskiBroj.text()
        adresa = self.txtAdresa.text()
        brojTelefona = self.txtBrojTelefona.text()
        brojKartice = self.txtBrojKartice.text()
        email = self.txtEmail.text()

        if(korisnickoIme and lozinka and ime and prezime and drzava and postanskiBroj and adresa and brojKartice and brojTelefona and email):
            korisnik = Korisnik.Korisnik()
            korisnik.registracijaKorisnika(korisnickoIme, lozinka, ime, prezime, email, drzava, postanskiBroj, brojTelefona, brojKartice, adresa)
            self.prijava = ui_login.Ui_Prijava()
            self.prijava.show()
            self.close()
        else:
            self.Upozorenje('Upozorenje', 'Niste unjeli sve podatke!')


    def Upozorenje(self, naziv, tekst):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(naziv)
        msgBox.setText(tekst)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

